# TCL File Generated by Component Editor 18.1
# Wed Nov 06 22:03:08 CET 2019
# DO NOT MODIFY


# 
# WS2812_Driver "ws2812_driver" v1.1
# LOCHE Jeremy 2019.11.06.22:03:08
# A ws2812 driver on avalon MM bus. 3 control registers and memory ban 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module WS2812_Driver
# 
set_module_property DESCRIPTION "A ws2812 driver on avalon MM bus. 3 control registers and memory ban "
set_module_property NAME WS2812_Driver
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "LOCHE Jeremy"
set_module_property DISPLAY_NAME ws2812_driver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL WS2812_Avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file WS2812_Avalon.v VERILOG PATH WS2812_Avalon.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter LED_MAX_NUMBER INTEGER 200 "Max number of LEDs in the chain. Defines the size of the color register bank"
set_parameter_property LED_MAX_NUMBER DEFAULT_VALUE 200
set_parameter_property LED_MAX_NUMBER DISPLAY_NAME LED_MAX_NUMBER
set_parameter_property LED_MAX_NUMBER TYPE INTEGER
set_parameter_property LED_MAX_NUMBER UNITS None
set_parameter_property LED_MAX_NUMBER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LED_MAX_NUMBER DESCRIPTION "Max number of LEDs in the chain. Defines the size of the color register bank"
set_parameter_property LED_MAX_NUMBER HDL_PARAMETER true
add_parameter LED_ADDR_W INTEGER 8 "Avalon address bus size for the registers. Must be CEIL( log2(3+LED_MAX_NUMBER))"
set_parameter_property LED_ADDR_W DEFAULT_VALUE 8
set_parameter_property LED_ADDR_W DISPLAY_NAME LED_ADDR_W
set_parameter_property LED_ADDR_W TYPE INTEGER
set_parameter_property LED_ADDR_W UNITS None
set_parameter_property LED_ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LED_ADDR_W DESCRIPTION "Avalon address bus size for the registers. Must be CEIL( log2(3+LED_MAX_NUMBER))"
set_parameter_property LED_ADDR_W HDL_PARAMETER true
add_parameter LED_DATA_W INTEGER 24 "Number of bits for the LED color: 24bits for GRB and 32 bits RGBW"
set_parameter_property LED_DATA_W DEFAULT_VALUE 24
set_parameter_property LED_DATA_W DISPLAY_NAME LED_DATA_W
set_parameter_property LED_DATA_W TYPE INTEGER
set_parameter_property LED_DATA_W UNITS None
set_parameter_property LED_DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LED_DATA_W DESCRIPTION "Number of bits for the LED color: 24bits for GRB and 32 bits RGBW"
set_parameter_property LED_DATA_W HDL_PARAMETER true
add_parameter CLK_FREQUENCY INTEGER 50000000 "Input Clock frequency. Used to generate WS2812 driving timings."
set_parameter_property CLK_FREQUENCY DEFAULT_VALUE 50000000
set_parameter_property CLK_FREQUENCY DISPLAY_NAME CLK_FREQUENCY
set_parameter_property CLK_FREQUENCY TYPE INTEGER
set_parameter_property CLK_FREQUENCY UNITS None
set_parameter_property CLK_FREQUENCY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_FREQUENCY DESCRIPTION "Input Clock frequency. Used to generate WS2812 driving timings."
set_parameter_property CLK_FREQUENCY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clk
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave address address Input LED_ADDR_W
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave readdata readdata Output 32
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 32
add_interface_port avalon_slave waitrequest waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point external_connexion
# 
add_interface external_connexion conduit end
set_interface_property external_connexion associatedClock ""
set_interface_property external_connexion associatedReset ""
set_interface_property external_connexion ENABLED true
set_interface_property external_connexion EXPORT_OF ""
set_interface_property external_connexion PORT_NAME_MAP ""
set_interface_property external_connexion CMSIS_SVD_VARIABLES ""
set_interface_property external_connexion SVD_ADDRESS_GROUP ""

add_interface_port external_connexion led_dout output Output 1

